/* SPDX-License-Identifier: GPL-3.0-or-later */
/* Generated by cbindgen from crates/plymouth-3dboot-capi; do not edit. */

#ifndef PLYMOUTH_3DBOOT_H
#define PLYMOUTH_3DBOOT_H




#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

// ABI version: the major version, incremented on every incompatible change
// to the C API; the shared library is libplymouth_3dboot.so.<major>.
#define P3B_ABI_VERSION 0 // x-release-please-major

// Largest renderer width or height. Colour plus depth take 8 bytes per
// pixel, so 8192 x 8192 needs 512 MiB; allocation failure would abort the
// host process, so sizes are bounded well below the core library's limit.
#define P3B_MAX_SIZE 8192

// Result of a `p3b_*` call. On anything but `P3B_STATUS_OK`,
// `p3b_last_error()` describes the problem.
typedef enum p3b_status {
  // Success.
  P3B_STATUS_OK = 0,
  // A required pointer argument was NULL.
  P3B_STATUS_NULL_POINTER = 1,
  // An argument was out of range or inconsistent.
  P3B_STATUS_INVALID_ARGUMENT = 2,
  // A string argument was not valid UTF-8.
  P3B_STATUS_INVALID_UTF8 = 3,
  // The model format is not supported.
  P3B_STATUS_UNSUPPORTED_FORMAT = 4,
  // A file could not be read.
  P3B_STATUS_IO = 5,
  // Model data could not be parsed.
  P3B_STATUS_PARSE = 6,
  // Rendering failed.
  P3B_STATUS_RENDER = 7,
  // The output buffer is too small for the requested image.
  P3B_STATUS_BUFFER_TOO_SMALL = 8,
  // An internal error (a bug): the call was aborted safely.
  P3B_STATUS_PANIC = 9,
} p3b_status;

// A loaded model (opaque). Create with `p3b_model_load_file` or
// `p3b_model_load_memory`; release with `p3b_model_free`.
typedef struct p3b_model p3b_model;

// Renders frames of one model (opaque). Create with `p3b_renderer_new`;
// release with `p3b_renderer_free`. A renderer must only be used by one
// thread at a time.
typedef struct p3b_renderer p3b_renderer;

// Supplies the contents of a file referenced by a model (e.g. an OBJ's
// material library) when loading from memory.
//
// Set `*data` and `*len` and return 0 if `name` exists, or return non-zero
// if it does not. The data must stay valid until the load call returns;
// the library copies it.
typedef int (*p3b_resolve_fn)(void *user_data, const char *name, const uint8_t **data, size_t *len);

// Shading model (`P3B_SHADING_*`).
typedef uint32_t p3b_shading;

// How playback time outside a clip is mapped (`P3B_WRAP_*`).
typedef uint32_t p3b_wrap;

// Where the camera comes from (`P3B_CAMERA_MODE_*`).
typedef uint32_t p3b_camera_mode;

// Rendering options. Start from `p3b_render_options_default()` and change
// fields as needed.
typedef struct p3b_render_options {
  // Shading model.
  p3b_shading shading;
  // Background colour as R, G, B, A bytes (straight alpha).
  uint8_t background[4];
  // Non-zero to cull back faces (double-sided materials never are). An
  // integer rather than `bool`, so that any byte value is valid.
  uint8_t cull_back_faces;
  // Clip playback wrap mode.
  p3b_wrap wrap;
  // Camera mode.
  p3b_camera_mode camera_mode;
  // `P3B_CAMERA_MODE_FRAMED`: direction from the camera towards the model.
  float view_direction[3];
  // `P3B_CAMERA_MODE_LOOK_AT`: camera position.
  float eye[3];
  // `P3B_CAMERA_MODE_LOOK_AT`: point looked at.
  float target[3];
  // `P3B_CAMERA_MODE_LOOK_AT`: up direction.
  float up[3];
  // Vertical field of view in radians; 0 or less for orthographic
  // (framed mode only).
  float fov_y;
  // `P3B_CAMERA_MODE_LOOK_AT`: near and far clip distances.
  float z_near;
  // See `z_near`.
  float z_far;
  // Supersampling anti-aliasing: samples per axis, 1 (off) to 8. Cost
  // grows with its square.
  uint8_t antialias;
  // Rendering threads (1 = single-threaded, up to 64). The output does
  // not depend on it.
  uint8_t threads;
} p3b_render_options;

// Layout of the pixels written by `p3b_render_frame` (`P3B_PIXEL_FORMAT_*`).
typedef uint32_t p3b_pixel_format;

// A rectangle of pixels: `width × height` pixels from column `x`, row `y`.
typedef struct p3b_rect {
  // First column.
  uint32_t x;
  // First row.
  uint32_t y;
  // Width in pixels (0 for an empty rectangle).
  uint32_t width;
  // Height in pixels (0 for an empty rectangle).
  uint32_t height;
} p3b_rect;

// Bytes R, G, B, A (straight alpha).
#define P3B_PIXEL_FORMAT_RGBA8888 0

// Bytes B, G, R, A (straight alpha).
#define P3B_PIXEL_FORMAT_BGRA8888 1

// One native-endian `uint32_t` per pixel, `0xAARRGGBB`, with colour
// premultiplied by alpha (Plymouth's pixel-buffer format).
#define P3B_PIXEL_FORMAT_ARGB32_PREMULTIPLIED 2

// Material colours as authored (self-illuminated).
#define P3B_SHADING_UNLIT 0

// Diffuse lighting.
#define P3B_SHADING_LAMBERT 1

// Diffuse lighting plus specular highlights.
#define P3B_SHADING_BLINN_PHONG 2

// Repeat the clip.
#define P3B_WRAP_LOOP 0

// Hold the first/last pose.
#define P3B_WRAP_CLAMP 1

// Play forwards, then backwards.
#define P3B_WRAP_PING_PONG 2

// Frame the whole (animated) model, looking along `view_direction`.
#define P3B_CAMERA_MODE_FRAMED 0

// Look from `eye` at `target` with `up`.
#define P3B_CAMERA_MODE_LOOK_AT 1

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// The library version as a NUL-terminated string (e.g. `"0.1.0"`). The
// string is static: do not free it.
const char *p3b_version(void);

// The ABI version of the loaded library; compare with
// `P3B_ABI_VERSION` from the header to detect mismatches.
uint32_t p3b_abi_version(void);

// The message describing the last failed `p3b_*` call on this thread (an
// empty string after a successful call). The pointer stays valid until the
// next `p3b_*` call on the same thread; do not free it.
const char *p3b_last_error(void);

// Loads a model file (`.obj` or `.dae`, chosen by extension); side files
// are read relative to its directory. On success `*out` receives the model
// (free it with `p3b_model_free`); on failure it is set to NULL.
//
// # Safety
//
// `path` must be a NUL-terminated string and `out` a valid pointer.
enum p3b_status p3b_model_load_file(const char *path, struct p3b_model **out);

// Loads a model from `len` bytes at `data`. `format` is `"obj"` or `"dae"`.
// Files the model refers to are requested from `resolve` (may be NULL: no
// side files) with `user_data`. On success `*out` receives the model; on
// failure it is set to NULL.
//
// # Safety
//
// `format` must be a NUL-terminated string, `data` must point to `len`
// readable bytes (or be NULL with `len == 0`), `resolve` must be NULL or a
// valid callback honouring its contract, and `out` a valid pointer.
enum p3b_status p3b_model_load_memory(const char *format,
                                      const uint8_t *data,
                                      size_t len,
                                      p3b_resolve_fn resolve,
                                      void *user_data,
                                      struct p3b_model **out);

// Frees a model. NULL is ignored.
//
// # Safety
//
// `model` must be NULL or a pointer from a `p3b_model_load_*` call that has
// not been freed, and no renderer may still use it.
void p3b_model_free(struct p3b_model *model);

// Number of animation clips in the model (0 for NULL).
//
// # Safety
//
// `model` must be NULL or a live model.
size_t p3b_model_clip_count(const struct p3b_model *model);

// Stores the duration in seconds of clip `index` in `*seconds`.
//
// # Safety
//
// `model` must be NULL or a live model; `seconds` a valid pointer.
enum p3b_status p3b_model_clip_duration(const struct p3b_model *model,
                                        size_t index,
                                        float *seconds);

// Adds a clip (as the last one) spinning the whole model one turn about the
// axis `(x, y, z)` through the origin every `period` seconds.
//
// # Safety
//
// `model` must be NULL or a live model not used by a renderer.
enum p3b_status p3b_model_add_turntable(struct p3b_model *model,
                                        float x,
                                        float y,
                                        float z,
                                        float period);

// Stores the model's bounding box at rest (world units, without a floor
// added by `p3b_model_add_floor`) in `min[3]` and `max[3]`.
//
// # Safety
//
// `model` must be NULL or a live model; `min` and `max` must point to three
// writable floats each.
enum p3b_status p3b_model_bounds(const struct p3b_model *model, float *min, float *max);

// Number of warnings produced while loading (0 for NULL).
//
// # Safety
//
// `model` must be NULL or a live model.
size_t p3b_model_warning_count(const struct p3b_model *model);

// Warning `index` as a NUL-terminated string owned by the model (valid
// until it is freed), or NULL if out of range.
//
// # Safety
//
// `model` must be NULL or a live model.
const char *p3b_model_warning(const struct p3b_model *model, size_t index);

// Adds a floor under the model: a square of the sRGB colour `rgb` (3
// bytes) just below the model's lowest point over its clips, with a half
// extent of `size` (> 0) times the model's horizontal radius. Add it after
// any turntable. The floor stays fixed while the model moves, is ignored
// when framing the camera, and costs little per frame.
//
// # Safety
//
// `model` must be NULL or a live model not used by a renderer; `rgb` must
// point to 3 readable bytes.
enum p3b_status p3b_model_add_floor(struct p3b_model *model, const uint8_t *rgb, float size);

// The default options: unlit shading on opaque black, back-face culling,
// looping, and a camera framing the model from the front right, slightly
// above, with a 0.7 rad field of view.
struct p3b_render_options p3b_render_options_default(void);

// Creates a renderer for `model` producing `width × height` images and
// playing clip `clip` (pass `SIZE_MAX`, i.e. `(size_t)-1`, for no
// animation). `options` may be NULL for the defaults.
//
// The model must stay alive, and must not be modified (e.g. by
// `p3b_model_add_turntable`), until the renderer is freed.
//
// # Safety
//
// `model` must be NULL or a live model satisfying the above; `options`
// NULL or valid; `out` a valid pointer.
enum p3b_status p3b_renderer_new(const struct p3b_model *model,
                                 size_t clip,
                                 uint32_t width,
                                 uint32_t height,
                                 const struct p3b_render_options *options,
                                 struct p3b_renderer **out);

// Frees a renderer. NULL is ignored.
//
// # Safety
//
// `renderer` must be NULL or a live renderer.
void p3b_renderer_free(struct p3b_renderer *renderer);

// Renders the frame at playback time `time` (seconds) into `dst`, which
// holds `dst_len` bytes with rows `stride` bytes apart (at least
// `width * 4`), in `format`. Bytes beyond each row's `width * 4` are left
// untouched.
//
// # Safety
//
// `renderer` must be NULL or a live renderer (whose model is still alive)
// not used concurrently; `dst` must point to `dst_len` writable bytes.
enum p3b_status p3b_render_frame(struct p3b_renderer *renderer,
                                 double time,
                                 uint8_t *dst,
                                 size_t dst_len,
                                 size_t stride,
                                 p3b_pixel_format format);

// Like `p3b_render_frame`, but writes only the pixels that changed since
// this renderer's previous frame, and stores their bounding rectangle in
// `*damage` (width and height 0 if nothing changed). Use it to update
// only part of the screen.
//
// `dst` must hold the previous frame of this renderer, as written by
// `p3b_render_frame` or `p3b_render_frame_incremental` with the same
// `stride` and `format`. The renderer's first frame is written entirely.
// On error, nothing is written to `dst` and `*damage` is the whole image.
//
// # Safety
//
// As for `p3b_render_frame`; `damage` must be a valid pointer.
enum p3b_status p3b_render_frame_incremental(struct p3b_renderer *renderer,
                                             double time,
                                             uint8_t *dst,
                                             size_t dst_len,
                                             size_t stride,
                                             p3b_pixel_format format,
                                             struct p3b_rect *damage);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* PLYMOUTH_3DBOOT_H */
